version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRESS_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - "5432:5432"
